{{- if .Values.additionalScrapeConfigs.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.additionalScrapeConfigs.name | default "monitoring-additional-scrape-config" }}
  labels:
{{ include "monitoring.labels" . | indent 4 }}
  annotations:
    monitoring.elliott.haus/managed-by: gitops
    monitoring.elliott.haus/purpose: annotation-discovery
stringData:
  {{ .Values.additionalScrapeConfigs.key | default "scrape-config.yaml" }}: |
{{- if .Values.additionalScrapeConfigs.data }}
{{ .Values.additionalScrapeConfigs.data | indent 4 }}
{{- else }}
{{- /* Fallback to sensible defaults if data not provided */ -}}
{{ include "monitoring.defaultScrapeConfig" . | indent 4 }}
{{- end }}
{{- end }}
