apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sealed-secrets-web.fullname" . }}
  labels:
    {{- include "sealed-secrets-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sealed-secrets-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sealed-secrets-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --controller-name={{ .Values.sealedSecrets.controllerName }}
            - --controller-namespace={{ .Values.sealedSecrets.controllerNamespace }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
