packages:
  - 'apps/*'
  - 'libs/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sqlite3
  - unrs-resolver
