{{- if .Values.ingress.cors.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "finances.fullname" . }}-cors
  labels:
    {{- include "finances.labels" . | nindent 4 }}
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "HEAD"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "CONNECT"
      - "OPTIONS"
      - "TRACE"
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    accessControlAllowOriginList:
{{ toYaml .Values.ingress.cors.allowOrigins | indent 6 }}
    accessControlMaxAge: 100
    addVaryHeader: true
{{- end }}
