apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "finances.fullname" . }}-data
  labels:
    {{- include "finances.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
