{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: finances-secrets
  labels:
    {{- include "finances.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded values - use: echo -n 'value' | base64
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  cookie-secret: {{ .Values.secrets.cookieSecret | b64enc | quote }}
  plaid-client-id: {{ .Values.secrets.plaidClientId | b64enc | quote }}
  plaid-secret: {{ .Values.secrets.plaidSecret | b64enc | quote }}
{{- end }}
