{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: pghero-secrets
  labels:
    {{- include "pghero.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgres://{{ .Values.database.user }}:{{ required "database.password is required when createSecret is true" .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
{{- end }}
