replicaCount: 1

image:
  repository: ethanelliottio/finances-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    kubernetes.io/ingress.class: 'nginx'
  hostname: 'finances.home.ee'

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
