---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: split-db-secrets
  namespace: elliott-haus
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  encryptedData:
    db-password: AgAxHqnSV+NEyfcNPMicWAvbXVv5D3PysGnrY2ndCYF53/cSIph5O+EcWnRcQ4RipxjMYgwyUuCJmpsjefLHiBi8fuddsdGYrKnZK3sVKlS+kHPRJoZ3Tkey4zsqOf9WPgcl3lu6on1hIv+/KxtsCmzqy9cXSQPDbq5MDTBIljJuChl2JOSwB4U6LpbLSwr0L3i3LR6RjZW12W75zWh3Sj7g5yPxP2gSZSKCoHsW/43VN2wrFmjmNBRi8TioHeoGoPxCWdr+cNAr1oMNNVj0Quy7TTOxRLcMsxuxsfxvI504M7d9xp/2iG5SMHE86xyvzWbzdD8IltcEsUp0H/wfLRA1t7xJh8PvW06OxneiB87Ika33Lpd6osyGSL7Gv1YRGU/KD+cugkyUT0AQqbMCO0QwLPzOcE61i+rQPAAloHTUs15q/VKpEg/tPWhJZbSgjjYaGZl9tvO3rir6Czo5StqUNBQqIa2NoTe5VceLRmUnOlPyozqbcFSIVTW/8h1WRWTvQL0FVnyy2SR7m/8fACH25gxMiqQ6pud1+u/JC/wAh8u/cloLooqw2hC2fGZP5IcQWHTsey9V674WquzQPsf5CPmWnFjm1rxGfhVK0azbvh8+JuqNcGpWeIhCgyzaD5v9y4C/8FL0Np96WLiRgxzCFWdsrxb0ND1XYNwIZLRChhC+eBFTaXSTL2yDwFy0GFi2gPi+V9vNH2ew4NQaNyuOnXaAlGSkPnBHKdHe0W9YAQ==
    jwt-secret: AgCXARTUztffztVojE0pfrIC530aErQhJ15UV1G65+GcQO8O0ye/U9ldgiBpK6+OuZ04enes50vQfvpM0EYtPEH61H6a63ZLWqFn81BMBIdFwSsNfx0RSZfLjyRM5JhYROSLKOHAoMIquS51/15dhFZT6eoVCyVTp0ENyR4X5CPTCO54H3vQ0J/mH5F5rTMPo5FeAdBSpDWORejCqWCZGKFflkO+hMK9Z+TOHT7GRaA4OMpouQtLGnsF/vkFAKP7JZJMayZTaQ5L28N7xAgNi8HP4N170GRAssdCtRdkaag7HsWAEa7vh/JiyBkEMg5a1hcRoOOCazlo9Ierm/fJPptaxuhMxUwXTlgpN77YPlPZp+aziON9HRxfMmY3N6d5xzWAADGfZPXtwYDKg3FRm16wsXF6fdD92chNoyODlUSqx5sb1r3Tzw/+OAX35DIl4UygzfNUkJ2Awn5SWt7I650lNIuVWzh3zSle0WiN5KKNJf+Vc5ksi2+qXngbBF1EBPMa9q4fFR13V705ioOvTM8KjdW84kQo6Ubnk+eWCu+m2CJhFhPAElMwW0pgQgHxzOEgSg+DcZ4KfIrtXynIxcZ3z2pUy8IShzMTfEj9nVXCZp6CRUdXoU9tZ4DleZ1mdAkHjJT4mT8zvOJblMBUIHd0KWwO6x9NG03ZTmFb/wg6RIoAQv3U5Ij3uFdKqQTS5G0tWAtvSjMz9pOcfY/oWGYc7RhxvRyEntL7WyerMaLMX3RLZc3df3zerQ5XU/ReUsPbnDGfk6JjM0kPeSJkGLJ/Cx+jNiW7NYD8/VI/p2wFSJ75s+tGjHkd
  template:
    metadata:
      name: split-db-secrets
      namespace: elliott-haus
