apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres-backup.fullname" . }}
  labels:
    {{- include "postgres-backup.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
