apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nvidia-gpu-exporter.fullname" . }}
  labels:
    {{- include "nvidia-gpu-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nvidia-gpu-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nvidia-gpu-exporter.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          ports:
            - name: http-metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http-metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility
            - name: LD_LIBRARY_PATH
              value: /usr/lib/wsl/lib:/usr/lib/wsl/drivers/nvdd.inf_amd64_1c978806815a7d2e
            - name: QUERY_FIELD_NAMES
              value: "name,index,uuid,temperature.gpu,utilization.gpu,utilization.memory,memory.total,memory.used,memory.free,power.draw,power.limit,fan.speed,pstate,clocks.current.graphics,clocks.current.memory,driver_version,pcie.link.gen.current,pcie.link.width.current"
          volumeMounts:
            - name: nvidia-smi
              mountPath: /usr/bin/nvidia-smi
              readOnly: true
            - name: nvidia-drivers
              mountPath: /usr/lib/wsl/drivers
              readOnly: true
            - name: wsl-lib
              mountPath: /usr/lib/wsl/lib
              readOnly: true
            - name: dev-dxg
              mountPath: /dev/dxg
      volumes:
        - name: nvidia-smi
          hostPath:
            path: /usr/bin/nvidia-smi
        - name: nvidia-drivers
          hostPath:
            path: /usr/lib/wsl/drivers
            type: Directory
        - name: wsl-lib
          hostPath:
            path: /usr/lib/wsl/lib
            type: Directory
        - name: dev-dxg
          hostPath:
            path: /dev/dxg
            type: CharDevice
