apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aritzia-scanner.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
