apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ip-monitor-db-secrets
  namespace: elliott-haus
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: ip-monitor-db-secrets
      namespace: elliott-haus
  encryptedData:
    db-password: AgCVDimP96BXEDwaCdW97SQXvbaMLViVyMEI6Xx+Sc+m4ic4sB7NB1WXxSy6GTyjYa3nia5oiLcCIaWphtqbgmITnRpX/LxUgHgWMaLVK7c86zXF3y6kFGHDIyWVObRaE5owkgNGD8kV7OfdgX8+qa2k/UL3K7ppichGRQ011CM3Og917XqWoOkiPKdC4SRuQyxWudJiub0ZiJ+21CrJ74QFu/tMWznHLdsDqNJhqQXGw55QZBrIjePkYR3vmmqWlZ7wqlLGilG4u6otWuzaF15auFgAaSdaE/iQpHfVTeM6JvBd+z5Ln6K0PO5dh/K3ahove5Lw8OXxEXTyktzvmGoHu0xVXhRDOqy81zqsTonfFxwRMuVkQ/g/TthHVfAfY/9z1tzvFl6WyjoY8L5cc263kzeXLWGYowKnRRq5KUIR0dBChrz9GHt72lhIraAH2jCTsUrw0zPmt4KkyKXgtswxxYWxd9TGD0aw6XiJUJ5hZpcYcbQ4LyUzCBDPzcLeAKtwdx3fmuFlHLO6PT0G2OeCWvlRQW6kLmt1doZN2zisnfQ5nI1SI/ktmbWRDzRfAPa+BeUagmamfZyq8XJYwtoTn2RV7ZduQS9uobC9p3TkjeAyG5rdFskhLTcZ9X2FTjcndmLOBYHrcIHVCNMvj7x2mqdfeTQr6lAIzG1OvPOh347UZdcR6vfsm5ulA/57hRmGvouXtHJ5KjO27RLMOtKc06Xm8P+F6wY=
