apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aranet-db-secrets
  namespace: elliott-haus
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: aranet-db-secrets
      namespace: elliott-haus
    type: Opaque
  encryptedData:
    # Sealed via https://sealed-secrets.elliott.haus (scope: elliott-haus/aranet-db-secrets).
    # To rotate: reseal a new value through that endpoint and replace this field.
    db-password: AgByByFchMOR4OEtTc5P1goKBKsmMbXP3UDhvoO8wWJ7cQTpi+tz9Bgsos3j6bi7aRbobvxRFDMOgBkTAu1IknwdreR2ImF3l2cPIP/R4o8ucW1HlouZkCAF09N3jyrS7y/o31xQZm9pyrsAz7GZ1FbkKX5VPd5H7YCF6bvxWOGL3hFVzNZat+j4ooTCBVZ5Z/D7/XnL16oMPfrRTtW11jUEIfSNu8cNq7m7z4lxPUQ+61bzfNWHcgoH/Tb2eBTW2xm/qCiIdeHugJ7VNK1ZXMWVpBkgTaZu2WRpNzWhw9muGbyPpT2WwdQd8j7u1sNsEKMngvHiPDp0Qp5nd9Ju6YtIznG36gSN4iK74HleeFhGz4wgFDA9A5MOAC+U+ok5bitwJeuoaKnCRrtO690eiL6fT3lv+hQzYT05bKhAfKfX+W+X6CPe6vbjQRwmIFxdm4E/ioxezx88ZGC6g6F83hQlNq7coGHslpdmfNUBulIobRnyPVYGYjwF/1DHMXyOHO51KTLvlj+mnKDAuvImRa5K1ET8sYn+8FQ+DFPHuJOyeXBwRX4O6yjTgryVzC1bTOTNrRZpV4U3sdRV3VivXj/FqaWMgEGgGXLpOLPAZElQfcQ0R1xBG1+qjZJ86/Uo02qHzko5osMJSVMDh7LHU6DH3M+gvESAAsGGyFw5dL+/7wRr0W7pH0qBtgwaq4dn8/DMzT8/N+nEeEvvdOgnvY1bDbiPdtd7vZWJleJA63emrYKZv8GFIt31F36hdktjYC0=
