{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "kube-state-metrics.fullname" .) }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
{{- end }}
