apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finances-frontend.fullname" . }}
  labels:
    {{- include "finances-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "finances-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "finances-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.configMap.enabled }}
          volumeMounts:
            - name: nginx-config
              mountPath: {{ .Values.configMap.mountPath }}
              subPath: {{ .Values.configMap.subPath }}
          {{- end }}
      {{- if .Values.configMap.enabled }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Values.configMap.name }}
      {{- end }}
