apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ntfy.fullname" . }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ntfy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ntfy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy
              readOnly: true
            - name: data
              mountPath: /var/cache/ntfy
      volumes:
        - name: config
          configMap:
            name: {{ include "ntfy.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "ntfy.fullname" . }}-data
