apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextdns-exporter-secrets
  namespace: elliott-haus
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: nextdns-exporter-secrets
      namespace: elliott-haus
  encryptedData:
    # NextDNS API key, sealed (strict scope) for nextdns-exporter-secrets/elliott-haus.
    api-key: AgA/G7Mw5e21gOyfY+sf1MtczLV5GTmAXUbM/syfkF+mo8SeVbu2XtpgapU7EQETUTQ3wR0cdriOVgxpmSIJr6SKSwHsV4X4Tgau79cRGrEN3o/v4i2osFSYi30VSHE2aoIMsiyB5CQYjbfTR+Or3fInAwqu40hKouB5kihqhvzrLsLMUyWtQ4ujlWMmiAeSR5zggb9erJjj1YT3lb7gE0tf3oar0i3r6oUO6KOcNiaWmCAsJAIQCHVKHf1XZfQDFHprVejYbUUQvipZYkioHrQH4lSRHGa9nXf5EQWg3ACN20TS/zCT4cH1HtXVIMXDhUWXBGaKJgqiY/RCKe8ZKAH8KLxuSJfpRt1UbFfQcWAue+EbMkVoHT/XTU0H7Trgmx3WxF1uM6SUT8jeJZnRpfTLob45NEdGnnQG8iSAYoVlQn7czNRGZXEDKEnZqqItn4hdL9jW0VEU+/YqwWCCjgrFnWv5tMa3t2dKt9dsiQQy5FQkcWGpNZSbBGAexyE3HNEAaqzFF3NRhG3m2RqPK9fpROgF1Xm3NaKMx2xFZHLmous9JuF3bZPO+yPZrHU3+VWw6UMFLGpXfi52UXWDq0qPkWPfW0brJqwd49cI3fP4f8xDWEUQNPFtiX3kJ4MrAWApfvauCZf+CwUpYjDaBag7UEmtfqGEkWb3Tij37IXoGQouI7rnqnKV2rLn8+m8x+A+Jr8lLkQQ+U5nl800KAkIPQMv+s3hmdbsE8RIexdVmsfRSF64TkTY
