---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wheel-db-secrets
  namespace: elliott-haus
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  encryptedData:
    db-password: AgCI58WJf1GEy6D6ZK7rafVDXPnjVds7eDF7GyjN+V+2g/3Um4MYTynV6HNek30K4OEc03GuM4uJrNB/JnJs4UTjOkwJXGf4osbvkedxhp3PYh1geqqvOyfYK3NOOIQPrDTt6rwd6BXmUJ91xFUapD76rMFdooyAIqsF0Sa2w745FMcPkAY76FLqv//w7de1mWt4sSUgYEBDsnphzpWmCp/j7nJdcdSJXPOTwASTO94LUKJOVrKEG5f5Wz82m6BagPTnuHdEOCk7yrlJaRAuujeGaJzpAJgQQVQKwEZhkVpfsdaybfVoOiMy6ju96neFrmNyh7PHZrHChkmF6i7ydT3TXIKM5Xl290/09XBR0VQ+87MS5VBo2o7bBWCt7CfrP3EOC6um+SmWL2Dbw2Gd3bTR0Tx6VqXtabD6xRrRWtLHtvU2PseE9UDCl7FBqi5sZ44BDH0b+dkI7QSryu+zD/mE6rGmzi8gbE2VZsMKmGtSuXKhKT6OJO+09k73Ws0HhQmOZSA1XJvHwzB6wQj7OLkV6kbivmDSTICSyT3pS5pvDaXsUUuLObD0qaEw4q0mqiEhj4RtmX2JaqX/hFox9J4THBjykR+k1e+d2cVZovHHKBU5PqAvqsHjy1ti2Ftz6Csbv+CrnH5yyB6kgHgIzUY5C4UtoGF8khsfuFsln/4PsfEZ5Lmm799zub2WLYaB1nZYIv7i8oyM+xN6LODkn9xsZ4yFOQykh8Ab/6TYscy1eJ92IW3J/A3IvlSNE9VgWsI=
    jwt-secret: AgCgt4d2FMmBr9tixY0GQAUDmWPGNkDl1FVT82UgFq9IHeueGX4Pp64yYifbDWUFBh+kU7W1Hpwr8ijE6+8Jm8q0BqXJqwW2+d+1XSPvBaiQCP+72S25U7H6wNnlF3dqFNsotnXEpRcS7lqMwDdfV5WBHxL7NlMyyTtszx0FZ3D3pP3wadYoiZ2/9DCJs+PAFoM6pGS0ZKyD9ueOAaAWbGldDr3dxoIDlJ5rQxv8/jQB+PMGQ7gxVdl0FWufsCJnf/Z6mWD9a/htMDdDmw3x/H/yPMreb4c9NSUs0TiD1/FWKp93aVinva55Y7waJ1B8llKmVUHIow3643oxijKtlctxNweQb7CvCS8BmCbqztw8bSx9d4CHDfcgzuudOnf4yIfth378wpNm1LFvJjvgm2U7FkUGQ0PPZIAmJqf1ZslUIVV8p86DB3KdH/bM2Ir2GXiVWI3Smco+q5XWXCetGhcT1iAalRdSP9errNlQqGYm6sOw3uaY4Dm7ke+k5yGT/Jcj2/Ano9/ztf5YFv9HFH0gYegGsGBsKuymOCRco6qAC7fwVNYisr6YnoDPzieo926WKu6UzzBvkR2HaMb3l2RiMVvQ6w87r3zH3ybXOJpaM+DbA6eGR0aY7kZk6tPF1ZluZkqbma+xhCUE/AqZ74M9KuMkdd1oXtYvvs4MQjQUUmkfRfBs5RR6RG4B/7YxPMwq0G8yQ7QbZOxnMkwDBXlqzV798f1zit1pxnj3+qY2cCHUF8dw2OB3fN1GkJiaV4u1BI1us8RMpv9mr4saiq1fKlz81MjV9zOBgAW3di4Fz7RnwTYfmFhHaAvmvAX6XIw=
  template:
    metadata:
      name: wheel-db-secrets
      namespace: elliott-haus
    type: Opaque
