---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trip-db-secrets
  namespace: elliott-haus
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  encryptedData:
    db-password: AgCMyR64d22PV7OCyaGYy8lX3GcScuExDgNbm8iHh18piyztcOuFOMS3kQMOKcixeLm5vdSqa2Cm0LRIipw8WaLkurF1+K4AwoG1fAaYjM5e9sFH7mSNYG50ErXgps+Qs0qn2FxHYbdo1q6ENRhopF/ODBQ/pZbCH7aZBui4VD0giQ1YepDHcTXhXzysf8MoEAzMqF0dczFEj8ilLgWYizNTouYPgXUObZTBD9pggoWkaF7aPIhSmZ7/gFHJ2pCgF4z9udP4RdVBh4+yvzGBhAx9J2lDHYD2WmImilOiGsK/f3dSNNL0hBZFJV6T7wrJBEvf8rnaLMnIqHQ5HcXqycjmA+0z0Pi8hGMEzE0PBo2Sjy6u2PWD18JEcv51klaid9cbestnvXA9/jpFuoEwBnenkdXmWHFx/2Bl2pYbuyECrHB3xpPWDboztt7bqIqoUuGuoP6olebru6wZ/7MzDZlYJBvWFvHRf6TPwTpLSJ7rSzDsTpwpj0u/5xDu1h/wcaUSi2MvQYAc31wmRd7zdKrirrzrY1F0q8/xUcJ+wP88hkS6oklw1ii5jO2WJ/nZitBb+7g310ZF5YEouY6m38oo0ohYtvEI7kFkTnEmXCLiweNs2sY88268Uo9uOHA0A5KgajsiD+Oya0GLZCSQ43l9uddYAFk7jabO6BfF39df5hRJxvKdbvABJS9QN6mBUbYYSU9MGCk5YIWdMMDDdtgZG9z3aX2kKRraBhx9mcENdL9CbFLLQp9siQ05wzqLuuQ=
    jwt-secret: AgB8A23Ejp+DNfZWKkwi7O8P/Oqm47BB1rF+0t260bzLu5TFpNqpVKYz4CNF6o0HQfKKZx4UddAO5mXTxiVfbEJ2F/ZeQr7dshCQDdVGDWDOYSMrMSOgGv35twysOeognNDNUad29XibiO52S+5nPxv5NbDGL+StDUhn4tzxMkaAq90H9YDbi3uYgtDdryQtQ/c+DdqZwLq3HstlNT3BG7ou70ChLlARWjZMya2g+c/IiJIaNAAkhWzAgrySdnAwuMJrbaDE1cQPSgEKTSURfM2Gi5uT0OLqoD/oRfNGDfI6vrHMMmWzSZr/2wpRz4DKZVpyks2vqNX5apAyG2B/pG6HYj1XNOSjjR75PrSnSW8f+koDhpnQui4lXaoJD+Fjpzfu9ZYn+fC3GRLYRQq9ssFOlmwEksSm60LObldUkgAIjR3QFVPTJw4QSmEom9A+edcduQGx7un5CHnLzANcHa38JfwMHKMtckCicMwB2KnbfxvoSs2C6sHY0BYxZfw5idNNyYbUoFTeRtgm2o18+jvGN4dOBsa7NexEM8+7LCsJ5HDQlEYkkUX+GnegFXqgwyf7NhulyNPOz16DtgQfQjoR8ikwfS7qhNEdrMcX/GOjUwaKbdHQPxgmS8+zZ3bHiTfey8K/TAh0NpIF7fCnKmsrPbjAyot20EHD4UsC5bgFry7EUyJoVFW5dlWxcCRmdyH9mRtTQQA8i3VmtFNXPSJTRwX++rzy0Wr7aWiWIgq7IU579/AuRnUlfDwdmjw5Vja+uQPja+Nju6/u+98RNfPjKXzT5Axf7P6Ju4jlfkCzN8CR7LsN52SHODuoHBOEBSw=
  template:
    metadata:
      name: trip-db-secrets
      namespace: elliott-haus
